return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")
		configs.setup({
			auto_install = true,
			ensure_installed = {
				"make",
				"c",
				"cpp",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"markdown",
				"markdown_inline",
				"go",
				"gomod",
				"gosum",
				"html",
				"css",
				"javascript",
				"php",
				"java",
				"csv",
				"json",
				"sql",
				"python",
				"bash",
				"gitignore",
				"dockerfile",
				"yaml",
				"latex",
				"norg",
				"scss",
				"svelte",
				"tsx",
				"typst",
				"vue",
				"regex",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
